# Generated by Django 5.2.8 on 2025-11-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tlno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
