# Generated by Django 5.2.8 on 2025-11-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_proveedores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
